"""Starlark representation of locked requirements.

@generated by rules_python pip_parse repository rule
from //lib/python:requirements_lock.txt
"""

load("@python39//:defs.bzl", "interpreter")
load("@rules_python//python/pip_install:pip_repository.bzl", "whl_library")

all_requirements = ["@pip_attrs//:pkg", "@pip_iniconfig//:pkg", "@pip_packaging//:pkg", "@pip_pluggy//:pkg", "@pip_py//:pkg", "@pip_pyparsing//:pkg", "@pip_pytest//:pkg", "@pip_tomli//:pkg"]

all_whl_requirements = ["@pip_attrs//:whl", "@pip_iniconfig//:whl", "@pip_packaging//:whl", "@pip_pluggy//:whl", "@pip_py//:whl", "@pip_pyparsing//:whl", "@pip_pytest//:whl", "@pip_tomli//:whl"]

_packages = [("pip_attrs", "attrs==21.4.0"), ("pip_iniconfig", "iniconfig==1.1.1"), ("pip_packaging", "packaging==21.3"), ("pip_pluggy", "pluggy==1.0.0"), ("pip_py", "py==1.11.0"), ("pip_pyparsing", "pyparsing==3.0.9"), ("pip_pytest", "pytest==7.1.2"), ("pip_tomli", "tomli==2.0.1")]
_config = {"download_only": False, "enable_implicit_namespace_pkgs": False, "environment": {}, "extra_pip_args": [], "isolated": True, "pip_data_exclude": [], "python_interpreter": "python3", "python_interpreter_target": None, "quiet": True, "repo": "pip", "repo_prefix": "pip_", "timeout": 600}
_annotations = {}
_bzlmod = False

def _clean_name(name):
    return name.replace("-", "_").replace(".", "_").lower()

def requirement(name):
    if _bzlmod:
        return "@@pip//:" + _clean_name(name) + "_pkg"
    return "@pip_" + _clean_name(name) + "//:pkg"

def whl_requirement(name):
    if _bzlmod:
        return "@@pip//:" + _clean_name(name) + "_whl"
    return "@pip_" + _clean_name(name) + "//:whl"

def data_requirement(name):
    if _bzlmod:
        return "@@pip//:" + _clean_name(name) + "_data"
    return "@pip_" + _clean_name(name) + "//:data"

def dist_info_requirement(name):
    if _bzlmod:
        return "@@pip//:" + _clean_name(name) + "_dist_info"
    return "@pip_" + _clean_name(name) + "//:dist_info"

def entry_point(pkg, script = None):
    if not script:
        script = pkg
    return "@pip_" + _clean_name(pkg) + "//:rules_python_wheel_entry_point_" + script

def _get_annotation(requirement):
    # This expects to parse `setuptools==58.2.0     --hash=sha256:2551203ae6955b9876741a26ab3e767bb3242dafe86a32a749ea0d78b6792f11`
    # down wo `setuptools`.
    name = requirement.split(" ")[0].split("=")[0].split("[")[0]
    return _annotations.get(name)

def install_deps(**whl_library_kwargs):
    whl_config = dict(_config)
    whl_config.update(whl_library_kwargs)
    for name, requirement in _packages:
        whl_library(
            name = name,
            requirement = requirement,
            annotation = _get_annotation(requirement),
            **whl_config
        )
