# yamllint disable rule:document-start
name: Bazel Build

# yamllint disable-line rule:truthy
on: push

jobs:
  buildchecks:
    name: Build Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Mount bazel cache  # Optional
        uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build
        run: bazel build //...
